### ISSUE TITLE
Should the package name be `eslint-find-rules`

### ISSUE THREAD

**Issue by sarbbottam** [sarbbottam/eslint-rule-finder#14]
Should the package name be `eslint-find-rules`? Similar to its predecessor `eslint-find-new-rules`?

Not sure, but I guess 
`eslint-find-rules [option] <filename>`
it sounds better than
`eslint-rule-finder [option] <filename>`

a verb seems better than a noun, in this case.

Thoughts?

**Comment by ta2edchimp** [comment]
Yeah, I completely agree. `eslint-find-rules` sounds more related and better in general.
